name: Jupytext Conversion

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  convert-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupytext jupyter nbconvert pandas matplotlib numpy seaborn cartopy netCDF4 shapely

    - name: Run Makefile in root directory
      run: |
        make all

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ready
        path: ready
